import type { Metadata } from "next";
import localFont from "next/font/local";
import { ClerkProvider, SignedIn, SignedOut, UserButton, SignInButton } from "@clerk/nextjs";
import "./globals.css";

// Import and configure the fonts
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// Metadata for the page
export const metadata: Metadata = {
  title: "SDG Classroom",
  description: "Generated by create next app",
};

// RootLayout Component
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
        <body className="bg-black text-white min-h-screen">
          {/* Header with the Sign In/Out Button */}
          <header className="flex justify-end items-center p-4">
            <SignedOut>
              {/* Custom Sign In Button using Clerk's SignInButton */}
              <SignInButton>
                <button className="bg-blue-600 hover:bg-blue-500 text-white font-semibold py-2 px-4 rounded-lg transition-colors">
                  Sign In
                </button>
              </SignInButton>
            </SignedOut>
            <SignedIn>
              {/* User Button (UserProfile or SignOut) */}
              <UserButton afterSignOutUrl="/" />
            </SignedIn>
          </header>
          
          {/* Main Content */}
          <main>
            {children}
          </main>
        </body>
      </html>
    </ClerkProvider>
  );
}
